{{- if .Values.server.serviceAccount.create }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.server.serviceAccount.name }}
  labels:
    {{- include "vshift.labels" . | nindent 4 }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vshift.fullname" . }}-server
  labels:
    {{- include "vshift.labels" . | nindent 4 }}
rules:
  - apiGroups: ["batch"]
    resources: ["jobs"]
    verbs: ["create", "get", "list", "watch", "delete"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vshift.fullname" . }}-server
  labels:
    {{- include "vshift.labels" . | nindent 4 }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.server.serviceAccount.name }}
    namespace: {{ .Release.Namespace }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vshift.fullname" . }}-server
{{- end }}
