apiVersion: v1
kind: Service
metadata:
  name: {{ include "vshift.fullname" . }}-server
  labels:
    {{- include "vshift.labels" . | nindent 4 }}
    app.kubernetes.io/component: server
spec:
  type: {{ .Values.server.service.type }}
  selector:
    {{- include "vshift.serverSelectorLabels" . | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.server.service.port }}
      targetPort: http
