from typing import Protocol


class MetricsCollector(Protocol):
    """Observability hooks; v1 uses a no-op implementation."""

    def increment_jobs_completed(self) -> None: ...

    def increment_jobs_failed(self) -> None: ...

    def set_queue_depth(self, depth: int) -> None: ...

    def observe_transcode_duration(self, seconds: float) -> None: ...

    def set_active_workers(self, count: int) -> None: ...
